### ISSUE TITLE
Send emails is broken.

### ISSUE THREAD

**Issue by cvgarciarea** [cristian99garcia/gmail-activity#17]
Clicking on "Send" button (tested by send it to only one person), shows the following error.
Note: this error is only shown when you try to send an email in a new thread, answering a existing thread works fine.

```
Traceback (most recent call last):
  File "/home/broot/sugar-build/activities/gmail-activity/redactor.py", line 545, in _send_cb
    mail["raw"] = base64.urlsafe_b64encode(message.as_string())
  File "/usr/lib64/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib64/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib64/python2.7/email/generator.py", line 164, in _write_headers
    v, maxlinelen=self._maxheaderlen, header_name=h).encode()
  File "/usr/lib64/python2.7/email/header.py", line 410, in encode
    value = self._encode_chunks(newchunks, maxlinelen)
  File "/usr/lib64/python2.7/email/header.py", line 370, in _encode_chunks
    _max_append(chunks, s, maxlinelen, extra)
  File "/usr/lib64/python2.7/email/quoprimime.py", line 97, in _max_append
    L.append(s.lstrip())
AttributeError: 'list' object has no attribute 'lstrip'
```

**Comment by Hrishi1999** [comment]
https://github.com/sugarlabs/gmail-activity/pull/29
